version: '3.8'

services:
  api:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=test
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
    volumes:
      - ./certificates:/https:ro
  signalrproxy:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - AppSettings__RabbitConnection=host=rabbitmq
      - AppSettings__HubUrl=https://api/my-hub
  service1:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - AppSettings__RabbitConnection=host=rabbitmq
  service2:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - AppSettings__RabbitConnection=host=rabbitmq
