version: '3.4'

services:
  api:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=test
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
      #- ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  signalrproxy:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - AppSettings__RabbitConnection=host=rabbitmq
  #  volumes:
  #    - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  service1:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - AppSettings__RabbitConnection=host=rabbitmq
  service2:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - AppSettings__RabbitConnection=host=rabbitmq
